wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712818834.262455
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.16
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
Model:
  desc: null
  value: RF
Hyperparameters:
  desc: null
  value:
    bootstrap: false
    max_depth: 64
    max_features: sqrt
    min_samples_leaf: 3
    min_samples_split: 6
    n_estimators: 307
