wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712818926.369039
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.16
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
Model:
  desc: null
  value: XGBoost
Hyperparameters:
  desc: null
  value:
    colsample_bytree: 0.62
    gamma: 0.48
    learning_rate: 0.35
    max_depth: 44
    min_child_weight: 8
    n_estimators: 480
    subsample: 0.59
    gpu_id: 0
