wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712819425.730135
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.16
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
Model:
  desc: null
  value: NN
Hyperparameters:
  desc: null
  value:
    activation: relu
    alpha: 0.077
    early_stopping: true
    hidden_layer_sizes:
    - 229
    - 255
    - 168
    learning_rate: adaptive
    max_iter: 11805
    solver: adam
    validation_fraction: 0.1
